server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecodb
    username: ecom1
    password: ecom123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: product_schema
        format_sql: true
  flyway:
    enabled: true
    schemas: product_schema
    locations: classpath:db/migration
    encoding: UTF-8
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web.exposure.include: health,info
  health:
    db.enabled: true
